version: '3.8'
services:
  sofa:
    build: .
    image: sofa-simulation
    container_name: sofa
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    privileged: true
